# Additional Information

## Data Description
- Each line includes the video title, the video poster, and every collaborator.
- No Music/Music Videos were included
- Podcast Channels, 2nd channels, and main channels are listed as the same poster.
- 172 Videos are included

## Data Collection
I found each collaboration by searching "ft. [collaborator]" in the Youtube search bar. Web scraping might be an easier, faster, and more efficient way to collect data in the future. However, sometimes the collaborator is not indicated in the title or description of the video and can only be seen in the Youtube Thumbnail so a combination of webscraping and manual work may be needed.

## Data File
```{r include=FALSE}
collabdata <- read.csv("YoutuberCollabWeb.csv", header = T)
write.csv2(collabdata, "./file.csv")

library(magrittr)
readLines("./file.csv") %>% 
  paste0(collapse="\n") %>% 
  openssl::base64_encode() -> encoded
```
[Download CSV](`r sprintf('data:text/csv;base64,%s', encoded)`)

## Coding Language Used
- R

## Packages Used
- igraph
- networkD3
- bookdown

## Resources
https://bookdown.org/yihui/bookdown/new-session.html
\n
http://www.htmlwidgets.org/index.html
\n
https://r-graph-gallery.com/network
