# Code
Here is the R Code I used

```{r, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("igraph")
# install.packages("networkD3")
# install.packages("bookdown")
library(igraph)
library(networkD3)
library(bookdown)
```

## Upload Data
```{r}
# upload data
collabdata <- read.csv("YoutuberCollabWeb.csv", header = T)
```

## Data Tidying
```{r}
# remove video title column
collabdata1 <- collabdata[-1]


# remove collaborators 2, 3, 4
collabdata2 <- collabdata1[1:2]

# change row names
colnames(collabdata2) <- c('from', 'to')
```

```{r}
# subset first and third row
collabdata3 <- collabdata1[c(1,3)]

# remove rows with no collaborator 2
collabdata3 <- collabdata3[!(is.na(collabdata3$`Collaborator.2`) | collabdata3$`Collaborator.2` ==""),]

# change row names
colnames(collabdata3) <- c('from', 'to')
```

```{r}
# subset first and fourth row
collabdata4 <- collabdata1[c(1,4)]

# remove rows with no collaborator 3
collabdata4 <- collabdata4[!(is.na(collabdata4$`Collaborator.3`) | collabdata4$`Collaborator.3` ==""),]

# change row names
colnames(collabdata4) <- c('from', 'to')
```

```{r}
# subset first and fifth row
collabdata5 <- collabdata1[c(1,5)]

# remove rows with no collaborator 4
collabdata5 <- collabdata5[!(is.na(collabdata5$`Collaborator.4`) | collabdata5$`Collaborator.4` ==""),]

# change row names
colnames(collabdata5) <- c('from', 'to')
```

```{r}
# Combine all rows
collabdata_merge <- rbind(collabdata2, collabdata3, collabdata4, collabdata5)
```

## Plot
```{r}
# Plot
p <- simpleNetwork(collabdata_merge, height="1200px", width="900px",        
                   Source = 1,                 # column number of source
                   Target = 2,                 # column number of target
                   linkDistance = 10,          # distance between node. Increase this value to have more space between nodes
                   charge = -900,                # numeric value indicating either the strength of the node repulsion (negative value) or attraction (positive value)
                   fontSize = 14,               # size of the node names
                   fontFamily = "serif",       # font og node names
                   linkColour = "#666",        # colour of edges, MUST be a common colour for the whole graph
                   nodeColour = "#69b3a2",     # colour of nodes, MUST be a common colour for the whole graph
                   opacity = 0.9,              # opacity of nodes. 0=transparent. 1=no transparency
                   zoom = T                    # Can you zoom on the figure?
)
```
